# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 800, 800))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("ui_files/elv.png"))
        self.background.setObjectName("background")
        self.elv1ShowFlr = QtWidgets.QLabel(self.centralwidget)
        self.elv1ShowFlr.setGeometry(QtCore.QRect(194, 245, 40, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.elv1ShowFlr.setFont(font)
        self.elv1ShowFlr.setAlignment(QtCore.Qt.AlignCenter)
        self.elv1ShowFlr.setObjectName("elv1ShowFlr")
        self.elv2ShowFlr = QtWidgets.QLabel(self.centralwidget)
        self.elv2ShowFlr.setGeometry(QtCore.QRect(566, 245, 40, 30))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.elv2ShowFlr.setFont(font)
        self.elv2ShowFlr.setAlignment(QtCore.Qt.AlignCenter)
        self.elv2ShowFlr.setObjectName("elv2ShowFlr")
        self.callElvBtn = QtWidgets.QPushButton(self.centralwidget)
        self.callElvBtn.setGeometry(QtCore.QRect(590, 20, 180, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.callElvBtn.setFont(font)
        self.callElvBtn.setObjectName("callElvBtn")
        self.waitingPsg = QtWidgets.QTableWidget(self.centralwidget)
        self.waitingPsg.setGeometry(QtCore.QRect(800, 0, 200, 800))
        self.waitingPsg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.waitingPsg.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.waitingPsg.setObjectName("waitingPsg")
        self.waitingPsg.setColumnCount(3)
        self.waitingPsg.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.waitingPsg.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.waitingPsg.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.waitingPsg.setHorizontalHeaderItem(2, item)
        self.waitingPsg.horizontalHeader().setDefaultSectionSize(60)
        self.waitingPsg.horizontalHeader().setMinimumSectionSize(60)
        self.waitingPsg.verticalHeader().setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Elevator Simulator"))
        self.elv1ShowFlr.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">10</span></p></body></html>"))
        self.elv2ShowFlr.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">10</span></p></body></html>"))
        self.callElvBtn.setText(_translate("MainWindow", "Add passenger"))
        item = self.waitingPsg.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "from"))
        item = self.waitingPsg.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "to"))
        item = self.waitingPsg.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "finish"))
