# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(340, 120)
        self.instrFrom = QtWidgets.QLabel(Form)
        self.instrFrom.setGeometry(QtCore.QRect(15, 15, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.instrFrom.setFont(font)
        self.instrFrom.setObjectName("instrFrom")
        self.instrTo = QtWidgets.QLabel(Form)
        self.instrTo.setGeometry(QtCore.QRect(15, 50, 140, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.instrTo.setFont(font)
        self.instrTo.setObjectName("instrTo")
        self.comboBoxFrom = QtWidgets.QComboBox(Form)
        self.comboBoxFrom.setGeometry(QtCore.QRect(220, 15, 60, 22))
        self.comboBoxFrom.setObjectName("comboBoxFrom")
        self.comboBoxFrom.addItem("")
        self.comboBoxFrom.addItem("")
        self.comboBoxFrom.addItem("")
        self.comboBoxFrom.addItem("")
        self.comboBoxFrom.addItem("")
        self.comboBoxFrom.addItem("")
        self.comboBoxFrom.addItem("")
        self.comboBoxFrom.addItem("")
        self.comboBoxFrom.addItem("")
        self.comboBoxFrom.addItem("")
        self.comboBoxTo = QtWidgets.QComboBox(Form)
        self.comboBoxTo.setGeometry(QtCore.QRect(145, 50, 60, 22))
        self.comboBoxTo.setObjectName("comboBoxTo")
        self.comboBoxTo.addItem("")
        self.comboBoxTo.addItem("")
        self.comboBoxTo.addItem("")
        self.comboBoxTo.addItem("")
        self.comboBoxTo.addItem("")
        self.comboBoxTo.addItem("")
        self.comboBoxTo.addItem("")
        self.comboBoxTo.addItem("")
        self.comboBoxTo.addItem("")
        self.comboBoxTo.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(280, 85, 40, 25))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.instrFrom.setText(_translate("Form", "Passenger is currently at floor"))
        self.instrTo.setText(_translate("Form", "His/Her target floor"))
        self.comboBoxFrom.setItemText(0, _translate("Form", "1"))
        self.comboBoxFrom.setItemText(1, _translate("Form", "2"))
        self.comboBoxFrom.setItemText(2, _translate("Form", "3"))
        self.comboBoxFrom.setItemText(3, _translate("Form", "4"))
        self.comboBoxFrom.setItemText(4, _translate("Form", "5"))
        self.comboBoxFrom.setItemText(5, _translate("Form", "6"))
        self.comboBoxFrom.setItemText(6, _translate("Form", "7"))
        self.comboBoxFrom.setItemText(7, _translate("Form", "8"))
        self.comboBoxFrom.setItemText(8, _translate("Form", "9"))
        self.comboBoxFrom.setItemText(9, _translate("Form", "10"))
        self.comboBoxTo.setItemText(0, _translate("Form", "1"))
        self.comboBoxTo.setItemText(1, _translate("Form", "2"))
        self.comboBoxTo.setItemText(2, _translate("Form", "3"))
        self.comboBoxTo.setItemText(3, _translate("Form", "4"))
        self.comboBoxTo.setItemText(4, _translate("Form", "5"))
        self.comboBoxTo.setItemText(5, _translate("Form", "6"))
        self.comboBoxTo.setItemText(6, _translate("Form", "7"))
        self.comboBoxTo.setItemText(7, _translate("Form", "8"))
        self.comboBoxTo.setItemText(8, _translate("Form", "9"))
        self.comboBoxTo.setItemText(9, _translate("Form", "10"))
        self.pushButton.setText(_translate("Form", "OK"))
